import type { Metadata } from "next";
import { Inter, Noto_Sans_SC, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/theme-provider"
 
const fontSansCn = Noto_Sans_SC({
  subsets: ["latin"],
  variable: "--font-sans-cn",
})
const fontSansEn = Inter({
  subsets: ["latin"],
  variable: "--font-sans-en",
})
const fontSansMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="zh-CN" >
      <head />
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSansEn.variable, fontSansCn.variable, fontSansMono.variable
        )}
        >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  </>
  );
}
